language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install --dev --prefer-source

script: ./vendor/bin/phpunit --coverage-text

notifications:
  email:
    - travis-ci@kitpages.fr
